server:
  port: 0
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_URL}
  application:
    name: activity-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${ACTIVITY_DB_URL}
    username: ${ACTIVITY_DB_USERNAME}
    password: ${ACTIVITY_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        use_sql_comments: false
        format_sql: false
  sql:
    init:
      mode: always