version: '3.8'

services:
  user-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: user-db
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    restart: always

  newsfeed-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: newsfeed-db
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    restart: always

  activity-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: activity-db
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1234
    ports:
      - "3308:3306"
    restart: always
  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"


volumes:
  mysql_pre_order:

networks:
  pre-order-network:
    driver: bridge