version: '3.8'

services:
  mysql:
    image: mysql:8.0.32
    container_name: preorder-db
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: preorder
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_pre_order:/var/lib/mysql

  redis:
    image: redis:7.2.4
    container_name: preorder-redis
    ports:
      - "6379:6379"

volumes:
  mysql_pre_order: