server:
  port: 8081

spring:
  application:
    name: pre-order
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  data:
    redis:
      port: 6379
      host: localhost

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          timeout: 5000
          auth: true
          connectiontimeout: 5000
          writetimeout: 5000
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}

jwt:
  secret: ${JWT_SECRET}
  access_token_expiration: 1000 * 60 * 30 # 0.5 Hours
  refresh_token_expiration: 1000 * 60 * 60 * 24 * 7 # 7 Days