server:
  port: 8081

spring:
  application:
    name: pre-order
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/preorder
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      port: 6379
      host: 127.0.0.1

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          timeout: 5000
          auth: true
          connectiontimeout: 5000
          writetimeout: 5000
    host: smtp.gmail.com
    username: 111
    password: 111
    port: 587
  sql:
    init:
      mode: always


jwt:
  secret: testhjgjkasgsfngadsgasgwgewgagdsgdsa34234afeasgajsgsafdss
  access_token_expiration: 1800000 # 0.5 Hours
  refresh_token_expiration: 604800000 # 7 Days
