upload:
    folder: ${user.dir}/uploads

jwt:
  secret: testhjgjkasgsfngadsgasgwgewgagdsgdsa34234afeasgajsgsafdss
  access_token_expiration: 1800000
  refresh_token_expiration: 604800000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          timeout: 5000
          auth: true
          connectiontimeout: 5000
          writetimeout: 5000
    host: smtp.gmail.com
    username: 123241234
    password: 12341234
    port: 587
server:
  port: 0