spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_URL}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${USER_DB_URL}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        use_sql_comments: false
        format_sql: false
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          timeout: 5000
          auth: true
          connectiontimeout: 5000
          writetimeout: 5000
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
  application:
    name: user-service
  sql:
    init:
      mode: always
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
upload:
    folder: ${user.dir}/uploads

jwt:
  secret: ${JWT_SECRET}
  access_token_expiration: ${JWT_ACCESS_EXPIRATION}
  refresh_token_expiration: ${JWT_REFRESH_EXPIRATION}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL}
server:
  port: 0